package com.crm.GomezdeMayora.week6.service;

import com.crm.GomezdeMayora.week6.Repositories.opportunityRepository;
import com.crm.GomezdeMayora.week6.model.Contact;
import com.crm.GomezdeMayora.week6.model.Opportunity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.transaction.Transactional;
import java.util.ArrayList;
import java.util.List;

@Component

public class opportunityDaoService {
    @Autowired
    private opportunityRepository opportunityrepository;

    public List<Opportunity> getOpportunities() {
        return opportunityrepository.findAll();
    }

    public Opportunity getOpportunityById(int id) {

        return opportunityrepository.findById(id).orElse(null); // if not opportunity found, return null. Exception is controlled by the interface.
    }
    public Opportunity findOpportunityByNameAndLastName(String name, String lastName) {
        return opportunityrepository.findOpportunityByNameAndLastName(name, lastName).orElse(null);
    }

    public Opportunity addOpportunity(Opportunity opportunity) {// By a lack of time the test will insert data in Database.

        //add opportunity.
        //return opportunity.

        // if not opportunity found, return null. Exception is controlled by the interface.
        Opportunity p =  findOpportunityByNameAndLastName(opportunity.getName(), opportunity.getLastName());
        //Check that there is no opportunity with the same name and lastname.
        if(p == null){
            opportunityrepository.save(opportunity);
            return findOpportunityByNameAndLastName(opportunity.getName(), opportunity.getLastName()); //To get the AutoGenerated id.
        }
        return null;
    }

}
